### ISSUE TITLE
Set up

### ISSUE THREAD

**Issue by esfandia** [NMAI-lab/SAVI#1]
I created a fresh repo with the source files we will start with. Please clone master and figure out how to make it work in your respective environment. Please give me the thumbs up in this Issue. When everybody is good to go I will close the Issue.

@pgavigan @ntartania @cruizm

**Comment by esfandia** [comment]
If you are using JEdit, you should be able to copy the rest of the files over from the "cleaning-robots" folder (but don't add them to your git watched files!), especially including the build.xml file, which will compile and package everything according to your own classpath settings.

**Comment by cruizm** [comment]
thumbs up! I have it running in my laptop.

**Comment by ntartania** [comment]
All set. Got the garbage picking agents to work. Boy does it flicker. (and also got my github account back!)
