### ISSUE TITLE
Initial Setup Documentation Updates

### ISSUE THREAD

**Issue by MikeVezina** [NMAI-lab/SAVI#108]
The following are some thoughts and suggestions for adding to the Setup wiki. It would be nice to get some feedback from everyone and possibly split some of these tasks up into other issues.

- [ ] We should have explicit instructions on how to run the simulation. These should be step-by-step instructions of how to run the code, starting with cloning the repo to your local machine. I think the usage of build tools (aka maven) would make this process a lot cleaner.

- [x] Need to include more informative instructions on how to set-up the debugger code.

- [x] The config.cfg settings should be explained somewhere in the wiki.

Additional thoughts (these would be good to consider, especially if we are planning on making this open source):

1. We should separate the simulator code from the Agent behaviour code. The simulator and the agent behaviour should ideally be two different components in their own repos, allowing them to evolve separately. This also allows each component to have it's own dedicated issues / pull requests / documentation.

2. We should really simplify the build process by using maven. Doing this would make obtaining the dependencies easier, and would also enforce organization of the file structure.

Let me know your thoughts on all of this. If I encounter any other issues, I will add a comment to this issue.

**Comment by esfandia** [comment]
Agreed on all of the above!

**Comment by ntartania** [comment]
If the agent behaviour is to go in its own repo it should be standalone. I mean, there should be some way of running it without the simulator. This could be using the debugging tool. 
Same for the simulator: for it to be a meaningful standalone program, we should be able to run it without Jason / BDI... This would require having a basic behaviour that can be put instead of Jason.

**Comment by pgavigan** [comment]
I have a few thoughts on these comments. I think they are good ideas but there are some complexities to them that will need to be addressed.

- I'll take on adding some more instructions for the debugger. I'll put these in the wiki. I can also add a page for the config file.
- With respect to the use of Maven for the project, we will need to work together to make sure that this happens seamlessly (and not break all of our development environments). Early in the project we made the decision not to enforce specific build tools or project structures on developers. If we do this we will need to reevaluate that decision. Additionally, I have not had any success finding Jason in Maven (and Jason has a computer specific configuration that would need to be addressed as well).
- Separation of the agent code and simulator code into separate repositories was discussed earlier in the project as well. We may be at the stage of the project where it is worth reconsidering. I agree with @ntartania that, if we do this, we will need to make sure that the two repositories are runnable in some form on their own. One area that concerns me a bit though is that there is an intrinsic linkage between the behaviour program and the representation of the agent in the simulated space - the perceptions and the actions. More specifically, the perceptions and actions structure in the behaviour program must align to the sensor and actuator implementation in the simulator or it wont work. Even if we want to separate these components into separate repositories, we can't ignore changes affecting perceptions and actions in the other. All of that said, I believe that there are solutions to these problems that we can discuss and potentially implement, but I want to make sure that we are on the same page on these issues before we make this decision.

**Comment by pgavigan** [comment]
Closed as remaining issues are duplicate.
