### ISSUE TITLE
Release 4 (Video): Sensor Malfunction

### ISSUE THREAD

**Issue by MikeVezina** [NMAI-lab/SAVI#119]

**Comment by MikeVezina** [comment]
What changes (if any) are we expecting on the agent/behaviour side to handle sensor malfunctions? 
Just trying to work out what the requirements/expectations are

**Comment by pgavigan** [comment]
I don't think we have a specific defined requirement for how the agents deal with sensor failure other than a desire that the agent should attempt to address the issue.

How issues are handled are a bit dependant on the nature of the issue but some ideas include:
- Detecting that there is an issue (it may not be obvious if it's just more sensor noise)
- Relying on older perception data
- Communicating with other agents that it has an issue and perhaps asking for help (for example, if the camera breaks on a UGV you could ask a UAV to direct you toward a threat or somewhere special for getting a repair)

These are suggestions only.

**Comment by pgavigan** [comment]
This issue likely has two components: On the simulation side (likely addressed by @cruizm and @gtrabes ) and also on the behaviour side (likely addressed by @MikeVezina with support from me).
