### ISSUE TITLE
PositionPerception Returning 0, 0, 0 When Sensors Don't Fail

### ISSUE THREAD

**Issue by MikeVezina** [NMAI-lab/SAVI#133]
UxVBehaviour, method 'getPositionWithError' returns an empty PVector (0, 0, 0) if the sensor does not fail.. This also indirectly affects the velocity perception due to the bearing calculation.

Desired behaviour is that you return the actual position if there is no sensor error.

https://github.com/NMAI-lab/SAVI/blob/985895cbe20491f73c6bb26500225cc301b169d2/saviSimulation/savi/jason_processing/UxVBehavior.java#L212

**Comment by pgavigan** [comment]
Resolved with PR.
