### ISSUE TITLE
Update CameraPerception and Add CompassAngle Perception

### ISSUE THREAD

**Issue by MikeVezina** [NMAI-lab/SAVI#134]
1. Is it possible to update the camera perception so that it includes an object identifier? (Or does this already exist?) This will allow for agents to keep track of which world objects it is looking at. It makes obstacle avoidance and multi-agent communication significantly easier and less computationally-intensive.

2. Is there a perception that informs the agent of the angle that it is currently facing? I've looked around and there doesn't seem to be a perception that provides this information. The only thing I see is velocity(BEARING), but it returns the overall bearing of the agent's position and NOT the compass angle of where the agent is facing.

Please see my comments in #135

**Comment by pgavigan** [comment]
The velocity perception provides both a speed and a direction. The direction is currently implemented as the direction that the agent is facing. This is the case even if the agent is not moving. In this case, the speed is reported as 0.

That said, @gtrabes and @cruizm can correct me if I didn't understand that correctly.

**Comment by MikeVezina** [comment]
@pgavigan that's what I initially thought as well, but the bearing provided by the velocity perception does not get affected by the direction you are facing.

For ex: you could have your agent spin in one location and the bearing stays constant. 

I have put up some changes in #136 to fix this, if you get a chance, could you take a look to see if it is correct!

**Comment by pgavigan** [comment]
Looking at it now. Good catch.

**Comment by cruizm** [comment]
@MikeVezina It was a simplification we made at the beginning of the project. We assumed that the robot moves in the direction it is facing.
We would be happy to remove that simplification if that allows you to implement advanced behaviors

**Comment by pgavigan** [comment]
Is this still an issue?

**Comment by MikeVezina** [comment]
Nope! Closed.
