### ISSUE TITLE
UAV Perceptions Not Correct

### ISSUE THREAD

**Issue by MikeVezina** [NMAI-lab/SAVI#137]
Not sure if this is a bug or intentional, but it looks like the UAV doesn't always recognize objects even though they are in the perception range. If I am missing something and this is correct behaviour, feel free to comment letting me know and close the issue.

See the attached image (two trees aren't being perceived this also lines up with the trees in the agent knowledge base so it's not just a visual issue): 

![image](https://user-images.githubusercontent.com/10552190/55160391-9c5f7c80-5139-11e9-94f7-34d388b3624d.png)

**Comment by ntartania** [comment]
I suspect that the bottom trees are hidden by the one at the top on the left. However, it's strange that the one on the top right would then be visible. Guillermo should be able to figure this out.

**Comment by MikeVezina** [comment]
It is a UAV, so because it has a top-down view, I would assume that it should see all of them as long as it is in the perception range! 

Side note, it might be good to draw the UAV on top of the trees since it will always be above objects on the ground

**Comment by pgavigan** [comment]
I believe that the UAV can technically have an altitude that is lower than the height of the tree, so I think there are times when a tree behind another tree might not be visible. That would be a very specific set of circumstances though.

**Comment by gtrabes** [comment]
Yes, in fact this is intentional, the trees are hidden by the others. In this simplistic approach the objects are hidden if the UxVs can't see their centroid. And yes, it depends on the altitude, an object covers other by its azimuth and elevation angles plus/minus its size.

**Comment by pgavigan** [comment]
Is this still an issue?

**Comment by pgavigan** [comment]
Resolved.
