### ISSUE TITLE
UAV Moves in Spirals & Randomly Freezes

### ISSUE THREAD

**Issue by MikeVezina** [NMAI-lab/SAVI#148]
1. The UAV moves in spirals rather than in straight lines. I'm going to guess that this is because we aren't turning the thrust off.

2. The UAV also seems to freeze randomly. Will look into this further.

**Comment by pgavigan** [comment]
I suspect that this may be addressed by PR #151. Please verify.

**Comment by pgavigan** [comment]
@ntartania and @cruizm: Can this be closed? We believe that this has been addressed.

The UAV no longer stops moving. The reason it looks like it moves in spirals is that it doesn't stop when it turns (therefore it generally moves in a curve shape).
