### ISSUE TITLE
Perception circles misaligned

### ISSUE THREAD

**Issue by pgavigan** [NMAI-lab/SAVI#154]
This is a screenshot with the perception circles shown misaligned. Based on the settings provided below (error was turned off) I believe that the perception circles are misaligned.

![Capture](https://user-images.githubusercontent.com/18585582/56831708-c6d74f00-6837-11e9-8494-3a0ea0e5447b.PNG)

This was generated using these settings:

NUMBER_TREES = 8
NUMBER_HOUSES = 0
NUMBER_THREATS = 5
X_PIXELS = 991
Y_PIXELS = 740
FRAME_RATE = 50
MAX_SPEED = 0.15
UGV_PERCEPTION_DISTANCE = 100
UAV_PERCEPTION_DISTANCE = 1200
WIFI_PERCEPTION_DISTANCE = 1200
NUMBER_UGV = 3
NUMBER_UAV = 1
RANDOM_SEED = 137
REASONING_CYCLE_PERIOD = 5
TREE_SIZE = 50
HOUSE_SIZE = 15
THREAT_SIZE = 10
ANTENNA_SIZE = 26
UGV_SIZE = 26
UAV_SIZE = 26
SENSORS_ERROR_PROB = 0
SENSORS_ERROR_STD_DEV = 0
WIFI_ERROR_PROB = 0.0

**Comment by MikeVezina** [comment]
After some investigation, it seems to be an issue with the Z coordinate. One possible reason is that the Z coordinate is not considered in the calculation for the position of the circles. See line 88-95 in UxV.java (master branch).

https://github.com/NMAI-lab/SAVI/blob/d37db779c85387401ea8300aa86a89b62992abe8/saviSimulation/savi/jason_processing/UxV.java#L92

**Comment by pgavigan** [comment]
Resolved by #159.
